version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-root:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /tests
    schedule:
      interval: weekly
    groups:
      npm-tests:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
